#!/usr/bin/env node

/**
 * Generates semantic version from git commit messages
 * Format: v0.{minor}.{patch}
 *
 * Patch increments for: fix, hotfix, patch, chore, build, docs
 * Minor increments for: feat and all other commits
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
  // Get all commit messages in chronological order
  const commitMessages = execSync('git log --pretty=format:"%s" --reverse', { encoding: 'utf8' })
    .trim()
    .split('\n')
    .filter(msg => msg.length > 0);

  // Keywords that trigger patch version increment (only actual fixes)
  const patchKeywords = ['fix', 'hotfix', 'patch'];

  let minor = 0;
  let patch = 0;

  // Analyze each commit message
  for (const message of commitMessages) {
    const lowerMessage = message.toLowerCase();

    // Check if it's a patch-type commit
    const isPatch = patchKeywords.some(keyword =>
      lowerMessage.includes(keyword)
    );

    if (isPatch) {
      patch++;
    } else {
      // All other commits (including feat) increment minor
      minor++;
    }
  }

  // Get short commit hash for build metadata
  const commitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();

  // Generate version string (clean semver, no build metadata)
  const version = `v0.${minor}.${patch}`;

  // Create TypeScript file
  const content = `// Auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION = '${version}';
export const MINOR_VERSION = ${minor};
export const PATCH_VERSION = ${patch};
export const COMMIT_HASH = '${commitHash}';
`;

  const outputPath = path.join(__dirname, '../lib/version.ts');
  fs.writeFileSync(outputPath, content, 'utf8');

  console.log(`✓ Generated version: ${version}`);
} catch (error) {
  console.error('Error generating version:', error.message);
  // Create fallback version if git is not available
  const fallbackContent = `// Auto-generated fallback version

export const VERSION = 'v0.0.0';
export const MINOR_VERSION = 0;
export const PATCH_VERSION = 0;
export const COMMIT_HASH = 'unknown';
`;

  const outputPath = path.join(__dirname, '../lib/version.ts');
  fs.writeFileSync(outputPath, fallbackContent, 'utf8');
  console.log('✓ Generated fallback version');
}
